# Generated by Django 5.1 on 2025-08-01 17:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_alter_claim_claim_amount'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='messages',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='received_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='messages',
            name='sender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sent_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='company',
            name='admin',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userpolicies',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claimant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='claims', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='regular',
            field=models.DecimalField(decimal_places=2, default=200, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpolicies',
            name='duration',
            field=models.PositiveIntegerField(default=3, help_text='duration in months'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpolicies',
            name='expiry_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='userpolicies',
            name='momo_number',
            field=models.CharField(default='0244', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='userpolicies',
            name='plan_type',
            field=models.CharField(choices=[('Premium', 'Premium'), ('Regular', 'Regular')], default='Premium', max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('Policy Payment', 'Policy Payment'), ('Claim Payout', 'Claim Payout')], max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('momo_number', models.CharField(max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('policy_subscription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='base.userpolicies')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
