# Generated by Django 5.1 on 2025-08-02 13:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_insurancepolicy_category_alter_claim_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insurancepolicy',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='policies', to='base.category'),
        ),
    ]
