# Generated by Django 5.1 on 2025-08-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_alter_insurancepolicy_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='adjustment_note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='claim',
            name='payout_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
