# Generated by Django 5.1 on 2025-08-05 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_claim_adjustment_note_claim_payout_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claim',
            name='approval_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='claim',
            name='claim_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
