# Generated by Django 5.1 on 2025-08-14 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_alter_claim_claimant_alter_claim_policy_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='insurancepolicy',
            old_name='coverage_amount',
            new_name='premium_coverage_amount',
        ),
        migrations.AddField(
            model_name='company',
            name='contact',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='insurancepolicy',
            name='regular_coverage_amount',
            field=models.DecimalField(decimal_places=2, default=15000, max_digits=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='transaction',
            name='claim',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='base.claim'),
        ),
        migrations.CreateModel(
            name='ClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='claim_documents/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='base.claim')),
            ],
        ),
    ]
