# Generated by Django 5.1 on 2025-08-14 12:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_rename_coverage_amount_insurancepolicy_premium_coverage_amount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insurancepolicy',
            name='duration',
        ),
    ]
